[WIP]: spatial prior
romain-lopez/DestVI-reproducibility pull request #1
Opened 2021-04-19 07:48 UTC by PierreBoyeau

2021-04-19 13:35 UTC, romain-lopez requested changes

2021-04-19 13:35 UTC, romain-lopez commented on simulations/spatial_prior/destvi_spatial/_model.py
> +class CustomTrainingPlan(TrainingPlan):
to remove?

2021-04-19 13:35 UTC, romain-lopez commented on simulations/spatial_prior/destvi_spatial/_model.py
> +        from scvi import settings
put import on top of file, run isort

2021-04-19 13:35 UTC, romain-lopez commented on simulations/spatial_prior/destvi_spatial/_model.py
> +        from scvi import settings
remove

2021-04-19 13:35 UTC, romain-lopez commented on simulations/spatial_prior/destvi_spatial/_model.py
> +        return CustomTrainingPlan
not necessary

2021-04-19 13:35 UTC, romain-lopez commented on simulations/spatial_prior/destvi_spatial/_model.py
> +    def get_metric(self):
@torch.nograd()?

2021-04-30 01:14 UTC, romain-lopez commented
@PierreBoyeau, any news on this end btw?

2021-04-30 11:06 UTC, PierreBoyeau commented
Hi @romain-lopez , I am harmonizing the code with the current codebase, so as to make my classes children of the updated classes. This should be done in a few hours!

2021-05-03 13:16 UTC, romain-lopez approved these changes

2021-05-03 13:18 UTC, merged